# Generated by Django 4.2.6 on 2023-11-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField()),
                ('genre', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
