# Generated by Django 4.2.6 on 2023-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_songs_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='0:00', max_length=10),
        ),
    ]
